# kubernetes deployment manifest file to recreate a deployment
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  name: javawebapp-deployment
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: javawebapp
  template:
    metadata:
      name: javawebapppod
      labels:
        app: javawebapp
    spec:
      containers:
        - name: javawebappcontainer
          image: ashokit/javawebapp
          ports:
            - containerPort: 8080
---
# node-port service manifest for javawebappsvc  
apiVersion: v1
kind: Service 
metadata:
  name: javawebappsvc
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
    - port: 80
      targetPort: 8080
...