# replicationController_manifest.yml
---
apiVersion: v1  
kind: ReplicationController
metadata:  
  name: javawebapp-rc 
spec:  
  replicas: 3
  selector:  
    app: javawebapp
  template:  
    metadata:
      name: javawebapppod
      labels:
        app: javawebapp
    spec:  
      containers: 
        - name: javawebappcontainer
          image: ashokit/javawebapp
          ports:  
            - containerPort: 8080
---
# node-port service manifest for javawebappsvc
apiVersion: v1
kind: Service 
metadata:
  name: javawebappsvc
spec:
  type: NodePort
  selector:
    app: javawebapp
  ports:
    - port: 80
      targetPort: 8080
...