# RBAC means Role-Based Access Control
# This manifest file creates a ClusterRoleBinding that binds a ClusterRole to a ServiceAccount.
# user accounts will be created and permissions will be assigned to them to perform the action
# using RoleBindings and ClusterRoleBindings. 


---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: admin-user
  namespace: kubernetes-dashboard
...